# Generated by Django 3.2.7 on 2022-05-27 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome completo')),
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='matrícula')),
                ('formacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='formação')),
                ('address_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='rua')),
                ('address_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='número')),
                ('address_district', models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
            ],
        ),
    ]
