# Generated by Django 3.2.7 on 2021-09-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        ('school_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=255, null=True, verbose_name='matrícula')),
                ('shift', models.CharField(choices=[('MANHÃ', 'MANHÃ'), ('TARDE', 'TARDE'), ('NOITE', 'NOITE')], max_length=255, verbose_name='turno')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Matemática', 'Matemática'), ('Inglês', 'Inglês'), ('Química', 'Química'), ('Espanhol', 'Espanhol'), ('Biologia', 'Biologia'), ('Gramática', 'Gramática'), ('Filosofia', 'Filosofia'), ('Física', 'Física'), ('História', 'História'), ('Português', 'Português'), ('Literatura', 'Literatura'), ('Geografia', 'Geografia'), ('Ciências', 'Ciências'), ('Artes', 'Artes'), ('Educação física', 'Educação física'), ('Redação', 'Redação')], max_length=255, verbose_name='materia')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_class.schoolclass', verbose_name='turma')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='professor')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClassSubjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='conteúdo')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comentário')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
                ('classwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classwork', to='school_work.schoolwork', verbose_name='trabalho de classe')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='school_work.schoolwork', verbose_name='trabalho de casa')),
                ('school_class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_class.schoolclasssubject', verbose_name='turma')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
                ('school_class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_class.schoolclasssubject', verbose_name='turma')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='aluno')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(verbose_name='presente')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
                ('school_class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_class.schoolclasssubject', verbose_name='turma')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='aluno')),
            ],
        ),
    ]
