# Generated by Django 3.2.7 on 2022-06-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('serie', 'identification', 'shift', 'ano')},
        ),
    ]
