# Generated by Django 3.2.7 on 2022-04-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectaveragegrade',
            name='student_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_class.studentsubject', verbose_name='matéria aluno'),
        ),
    ]
