# Generated by Django 3.2.7 on 2022-12-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='subject',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Inglês', 'Inglês'), ('Química', 'Química'), ('Espanhol', 'Espanhol'), ('Biologia', 'Biologia'), ('Gramática', 'Gramática'), ('Filosofia', 'Filosofia'), ('Física', 'Física'), ('História', 'História'), ('Português', 'Português'), ('Literatura', 'Literatura'), ('Geografia', 'Geografia'), ('Ciências', 'Ciências'), ('Artes', 'Artes'), ('Educação física', 'Educação física'), ('Redação', 'Redação'), ('Religião', 'Religião')], max_length=255, verbose_name='materia'),
        ),
    ]
