# Generated by Django 3.2.7 on 2022-12-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_class', '0004_classsubjecthistorypresence_register_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjecthistory',
            name='register_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de registro'),
        ),
    ]
