# Generated by Django 3.2.7 on 2022-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='número')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='cep')),
                ('creation_datetime', models.DateTimeField(editable=False, verbose_name='data de criação')),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('date_schedule', models.DateTimeField(blank=True, null=True, verbose_name='data agendada')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
            ],
        ),
    ]
