# Generated by Django 3.2.7 on 2022-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='date_end_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data início agendada'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='date_init_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data início agendada'),
        ),
    ]
