# Generated by Django 3.2.7 on 2021-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='matrícula')),
                ('responsible_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do responsável')),
                ('responsible_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='contato do responsável')),
                ('address_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='rua')),
                ('address_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='número')),
                ('address_district', models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
            ],
        ),
    ]
