# Generated by Django 3.2.7 on 2022-03-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome completo')),
                ('registration_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='matrícula')),
                ('responsible_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do responsável')),
                ('responsible_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='contato do responsável')),
                ('creation_datetime', models.DateTimeField(editable=False)),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.address', verbose_name='endereço')),
            ],
        ),
    ]
