# Generated by Django 3.2.7 on 2022-06-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do responsável'),
        ),
    ]
