# Generated by Django 3.2.7 on 2021-11-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cep'),
        ),
    ]
