# Generated by Django 3.2.7 on 2022-05-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='address_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rua'),
        ),
    ]
