# Generated by Django 3.2.7 on 2022-05-06 22:51

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220506_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.PositiveIntegerField(blank=True, default=student.models.random_string, null=True, unique=True, verbose_name='matrícula'),
        ),
    ]
