# Generated by Django 3.2.7 on 2022-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='identificação'),
        ),
        migrations.AddField(
            model_name='student',
            name='serie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='série'),
        ),
    ]
